### PR TITLE
locense -> license

### PR DESCRIPTION
**Pull request by spikespaz**
Sorry, glad I noticed. It passed `nix flake check`.

### CODE REVIEW

**Review by cathaysia — APPROVED** [review]

**Comment by cathaysia** [comment]
This project require linear history, that means you cannot create merge node(such as a commit start with "Merge xxx into xxx"). Could you solve these conflicts by git rebase?

**Comment by spikespaz** [comment]
@cathaysia Would you like me to create a new typo fix commit on master or rebase into the amended commit?

**Comment by cathaysia** [comment]
yes.

**Comment by spikespaz** [comment]
As you have protected master, I will squash and merge.

**Pull request merged**
